{% set name = "pycap-dss" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycap_dss-{{ version }}.tar.gz
  sha256: 21601972fa43b8aa74475771f6a173d2840a22d65170116eb69fa40724b7f5f8 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - ipython
    - jupyter
    - notebook
    - ipykernel
    - matplotlib-base
    - pyyaml
    - geopandas
    - numpy
    - scipy
    - pandas
    - gdal
    - fiona
    - rasterio >=1.0
    - rasterstats
    - shapely
    - rtree
    - pyproj >=2.0
    - pyshp
    - xlrd
    - openpyxl
    - requests

test:
  imports:
    - pycap
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/doi-usgs/pycap-dss
  license: CC0-1.0
  license_file: LICENSE.md
  summary: Analytical solutions for drawdown and sreamflow depletion with groundwater pumping
  description: |
    pycap-dss is a framework for analytical solutions of stream depletion and drawdown from high-capacity groundwater pumping wells.
  dev_url: https://github.com/doi-usgs/pycap-dss


extra:
  recipe-maintainers:
    - mnfienen
